#ifndef KEYBOARD_H
#define KEYBOARD_H

#include "stdafx.h"

namespace tadPole
{
	typedef int Key;	///< The tadPole representation of SDL_Key.

	#define KEY_A			 SDLK_a
	#define KEY_B			 SDLK_b
	#define KEY_C			 SDLK_c
	#define KEY_D			 SDLK_d
	#define KEY_E			 SDLK_e
	#define KEY_F			 SDLK_f
	#define KEY_G			 SDLK_g
	#define KEY_H			 SDLK_h
	#define KEY_I			 SDLK_i
	#define KEY_J			 SDLK_j
	#define KEY_K			 SDLK_k
	#define KEY_L			 SDLK_l
	#define KEY_M			 SDLK_m
	#define KEY_N			 SDLK_n
	#define KEY_O			 SDLK_o
	#define KEY_P			 SDLK_p
	#define KEY_Q			 SDLK_q
	#define KEY_R			 SDLK_r
	#define KEY_S			 SDLK_s
	#define KEY_T			 SDLK_t
	#define KEY_U			 SDLK_u
	#define KEY_V			 SDLK_v
	#define KEY_W			 SDLK_w
	#define KEY_X			 SDLK_x
	#define KEY_Y			 SDLK_y
	#define KEY_Z			 SDLK_z
	#define KEY_F1			 SDLK_F1
	#define KEY_F2			 SDLK_F2
	#define KEY_F3			 SDLK_F3
	#define KEY_F4			 SDLK_F4
	#define KEY_F5			 SDLK_F5
	#define KEY_F6			 SDLK_F6
	#define KEY_F7			 SDLK_F7
	#define KEY_F8			 SDLK_F8
	#define KEY_F9			 SDLK_F9
	#define KEY_F10			 SDLK_F10
	#define KEY_F11			 SDLK_F11
	#define KEY_F12			 SDLK_F12
	#define KEY_0			 SDLK_0
	#define KEY_1			 SDLK_1
	#define KEY_2			 SDLK_2
	#define KEY_3			 SDLK_3
	#define KEY_4			 SDLK_4
	#define KEY_5			 SDLK_5
	#define KEY_6			 SDLK_6
	#define KEY_7			 SDLK_7
	#define KEY_8			 SDLK_8
	#define KEY_9			 SDLK_9
	#define KEY_BACKSLASH	 SDLK_BACKSLASH
	#define KEY_BACKSPACE	 SDLK_BACKSPACE
	#define KEY_CAPSLOCK	 SDLK_CAPSLOCK
	#define KEY_COMMA		 SDLK_COMMA
	#define KEY_DELETE		 SDLK_DELETE
	#define KEY_DOWN		 SDLK_DOWN
	#define KEY_END			 SDLK_END
	#define KEY_EQUALS		 SDLK_EQUALS
	#define KEY_ESCAPE		 SDLK_ESCAPE
	#define KEY_BACKQUOTE	 SDLK_BACKQUOTE
	#define KEY_HOME		 SDLK_HOME
	#define KEY_INSERT		 SDLK_INSERT
	#define KEY_NUM0		 SDLK_KP_0
	#define KEY_NUM1		 SDLK_KP_1
	#define KEY_NUM2		 SDLK_KP_2
	#define KEY_NUM3		 SDLK_KP_3
	#define KEY_NUM4		 SDLK_KP_4
	#define KEY_NUM5		 SDLK_KP_5
	#define KEY_NUM6		 SDLK_KP_6
	#define KEY_NUM7		 SDLK_KP_7
	#define KEY_NUM8		 SDLK_KP_8
	#define KEY_NUM9		 SDLK_KP_9
	#define KEY_NUMDIVIDE	 SDLK_KP_DIVIDE
	#define KEY_NUMENTER	 SDLK_KP_ENTER
	#define KEY_NUMMINUS	 SDLK_KP_MINUS
	#define KEY_NUMMULTIPLY  SDLK_KP_MULTIPLY
	#define KEY_NUMPERIOD	 SDLK_KP_PERIOD
	#define KEY_NUMPLUS		 SDLK_KP_PLUS
	#define KEY_LALT		 SDLK_LALT
	#define KEY_LCTRL		 SDLK_LCTRL
	#define KEY_LEFT		 SDLK_LEFT
	#define KEY_LBRACKET	 SDLK_LEFTBRACKET
	#define KEY_LGUI		 SDLK_LGUI
	#define KEY_LSHIFT		 SDLK_LSHIFT
	#define KEY_MINUS		 SDLK_MINUS
	#define KEY_NUMLOCK		 SDLK_NUMLOCKCLEAR
	#define KEY_PAGEDOWN	 SDLK_PAGEDOWN
	#define KEY_PAGEUP		 SDLK_PAGEUP
	#define KEY_PERIOD		 SDLK_PERIOD
	#define KEY_PRINTSCREEN  SDLK_PRINTSCREEN
	#define KEY_RALT		 SDLK_RALT
	#define KEY_RCTRL		 SDLK_RCTRL
	#define KEY_RETURN		 SDLK_RETURN
	#define KEY_RGUI		 SDLK_RGUI
	#define KEY_RIGHT		 SDLK_RIGHT
	#define KEY_RBRACKET	 SDLK_RIGHTBRACKET
	#define KEY_RSHIFT		 SDLK_RSHIFT
	#define KEY_SCROLLLOCK	 SDLK_SCROLLLOCK
	#define KEY_SEMICOLON	 SDLK_SEMICOLON
	#define KEY_FRONTSLASH	 SDLK_SLASH
	#define KEY_SPACE		 SDLK_SPACE
	#define KEY_TAB			 SDLK_TAB
	#define KEY_UP			 SDLK_UP
	#define KEY_AMPERSAND	 SDLK_AMPERSAND
	#define KEY_ASTERISK	 SDLK_ASTERISK
	#define KEY_AT			 SDLK_AT
	#define KEY_CARET		 SDLK_CARET
	#define KEY_COLON		 SDLK_COLON
	#define KEY_DOLLAR		 SDLK_DOLLAR
	#define KEY_EXCLAIM		 SDLK_EXCLAIM
	#define KEY_GREATER		 SDLK_GREATER
	#define KEY_POUND		 SDLK_HASH
	#define KEY_LEFTPAREN	 SDLK_LEFTPAREN
	#define KEY_LESS		 SDLK_LESS
	#define KEY_PERCENT		 SDLK_PERCENT
	#define KEY_PLUS		 SDLK_PLUS
	#define KEY_QUESTION	 SDLK_QUESTION
	#define KEY_SINGLEQUOTE  SDLK_QUOTE
	#define KEY_DOUBLEQUOTE  SDLK_QUOTEDBL
	#define KEY_RIGHTPAREN	 SDLK_RIGHTPAREN
	#define KEY_UNDERSCORE	 SDLK_UNDERSCORE
}

#endif
